#!/bin/bash
echo "[Unit]
Description=Mount DO Volume $DROPLET_TAG-vol

[Mount]
What=/dev/disk/by-id/scsi-0DO_Volume_$DROPLET_TAG-vol
Where=/mnt/$MNT_DIR
Options=defaults,nofail,discard,noatime
Type=ext4

[Install]
WantedBy = multi-user.target" | tee /etc/systemd/system/mnt-$MNT_DIR.mount
systemctl daemon-reload
systemctl enable mnt-$MNT_DIR.mount
