#cloud-config
#


# Upgrade the instance on first boot (ie run apt-get upgrade)
# Default: false
# Aliases: apt_upgrade
package_update: true
package_upgrade: true


packages:
  - ufw

users:
  - name: borger
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIATgg/OtSV/cfGMs6HrjxYyFHcJuAynmJREIF+nyugmN Adrian@iMac
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBW4iCWVkQmwaShbJwNqISqS3P8aINLjCCaS9cmae5iJ Adrian@Adrians-MBP
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJUdZTJq1rXvGcQ7G+MJoEnBXkDr6bxX30SMfpzHpO7w paisley@htpc1

runcmd: 
  - echo "y" | ufw enable
  - ufw rule allow proto tcp to 0.0.0.0/0 port 2222
  - ufw default deny incoming
  - ufw default allow outgoing 
  - sed -i -e '/^#alias ll/s/^#//' /home/borger/.bashrc
  - sed -i -e '/^#Port/s/^.*$/Port 2222/' /etc/ssh/sshd_config
#  - systemctl restart sshd
  - export HOSTNAME=$(curl -s http://169.254.169.254/metadata/v1/hostname)
  - echo $HOSTNAME
  - export PUBLIC_IPV4=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
  - echo $PUBLIC_IPV4

power_state:
 delay: "+1"
 mode: reboot
 message: Bye Bye
 timeout: 30
 condition: True

